### ISSUE TITLE
Failed Cluster Start: Failed to add one or more helper nodes: runtime failed to start node 'k3d-portainer-serverlb'

### ISSUE THREAD

**Issue by yueyueaa** [phosae/kube-setup#2]
When creating a cluster with k3d, I encountered the following issue:

`Failed Cluster Start: Failed to add one or more helper nodes: runtime failed to start node 'k3d-portainer-serverlb': docker failed to start container for node 'k3d-portainer-serverlb': Error response from daemon: driver failed programming external connectivity on endpoint k3d-portainer-serverlb (6f550a0c0166d3d6ed0fa1a43842d4414c5b9e043d162e889321d57b187183ce): Error starting userland proxy:`

I found a solution to this problem by changing the port range from 30000-30100 to 3000-3010 in the bash command, and then re-executing the command, which allowed the cluster to be created successfully.

**The exact cause of this issue is not clear.😭** 
Maybe, changing the port range might have resolved a port conflict that was preventing the Docker containers from starting properly.

**Comment by phosae** [comment]
```shell
INFO[0000] Using config file - (k3d.io/v1alpha5#simple)
...
INFO[0004] Starting cluster 'k3d'
INFO[0004] Starting servers...
INFO[0004] Starting Node 'k3d-k3d-server-0'
INFO[0009] Starting agents...
INFO[0009] Starting Node 'k3d-k3d-agent-1'
INFO[0009] Starting Node 'k3d-k3d-agent-0'
INFO[0014] Starting helpers...
INFO[0014] Starting Node 'k3d-k3d-serverlb'
ERRO[0017] Failed Cluster Start: Failed to add one or more helper nodes: runtime failed to start node 'k3d-k3d-serverlb': docker failed to start container for node 'k3d-k3d-serverlb': Error response from daemon: driver failed programming external connectivity on endpoint k3d-k3d-serverlb (6e10b8ad7e10a34d1495a196f246b54ba31eccb3cae409569b0b19349a9424cf): Error starting userland proxy: listen tcp4 0.0.0.0:30028: bind: address already in use
```

it likely that some port on the host range in 30000-30100 haven't fulling released during teardown.
just wait some seconds and retry can solve the problem.

if not, use tools like lsof or netstat to check the occupied ports, release the ports by manually kill the processes, and retry.
